# Generated by Django 5.2.7 on 2025-11-22 21:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_goal_options_alter_note_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={'ordering': ['order', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['order', '-created_at']},
        ),
        migrations.AddField(
            model_name='goal',
            name='selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goal',
            name='goal_type',
            field=models.CharField(choices=[('static', 'Static'), ('progress', 'Progress')], default='static', max_length=16),
        ),
    ]
