# Generated by Django 5.2.7 on 2025-11-27 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='is_archived',
            new_name='archived',
        ),
    ]
